### ISSUE TITLE
Building issues with Visual Studio 2017

### ISSUE THREAD

**Issue by simonowen** [redcode/Zeta#1]
I understand that support for Visual Studio might still be a work in progress, particularly in regard to the recent compiler inspection commits.  I thought it might still be worth reporting the current issues, so they can be addressed.

#### warning C4003: not enough arguments for function-like macro invocation 'Z_DEFINE_STRICT_STRUCTURE'

I had to add a dummy variable to two structures definition to make it happy:
```cpp
Z_DEFINE_STRICT_STRUCTURE(
	int dummy;
) ZEmulatorDependency;
```
and:
```cpp
typedef struct {
	int dummy;
} ZMachineEmulatorABI;
```
---

#### warning C4311: 'type cast': pointer truncation from 'zuint8 *' to 'unsigned long'
in:
```cpp
#  define Z_OFFSET_OF(type, member) (((unsigned long int)&((type *)(1))->member) - 1)
```
long is a 32-bit type on 64-bit Windows.  To work around it I changed the cast to:
```cpp
#  define Z_OFFSET_OF(type, member) (((zusize)(unsigned long long)&((type *)(1))->member) - 1)
```
though I don't know if that'll be warning free in other compilers.

---

When used in conjunction with your Z80 core, the latest Z gives many reports of "error C2159: more than one storage class specified".  For example, in:
```cpp
static Z_INLINE zuint16 read_16bit(Z80 *object, zuint16 address)
	{return (zuint16)(READ_8(address) | (zuint16)READ_8(address + 1) << 8);}
```

Removing Z_INLINE from any line it complained about seemed to fix it, though that may cause a speed penalty if it's no longer inlined.  Possible a compiler inspection issue?

If you get a chance to build the Z80 core in a 64-bit project using Visual Studio 2017 (15.8.8), you should see the same issues.

**Comment by redcode** [comment]
Thanks Simon,

I've fixed `<Z/ABIs/generic/emulation.h>` so `ZEmulatorDependency` is no more empty and `ZMachineEmulatorABI` is now commented (it's not used for now).

The problem with `Z_OFFSET_OF` under Windows / x86-64 is more complicated, because `<Z/macros/language.h>` must not depend on `<Z/types/base.h>`. You have fixed the problem casting to `unsigned long long`, a type not available in all compilers, and `zusize`, which is declared in `<Z/types/base.h>`. This works OK for you because `<Z/types/base.h>` has been included at the time you use `Z_OFFSET_OF`, but `<Z/macros/language.h>` should be usable without including `<Z/types/base.h>`.

In Windows / x86-64 uses `LLP64`, which is, along `IP16L32`, the only C data model with different sizes for `long int` and `pointer`, so this last resort macro used in the case the compiler inspector doesn't provide an `offsetof()` built-in produces a warning. I have to think in a fix for this...

For now, I've added the built-in for offsetoff that Visual C++ uses in `<Z/compiler/inspection/compiler/modules/Visual C++.h>` and have solved there the `Z_INLINE` problem too.

These changes should fix your problems. Thanks for your help.

Please, tell me if everything is working OK.

**Comment by simonowen** [comment]
Thanks for the update, which solves the struct issue.  I'm using a slightly customised version of Z80 for code hooks (using LD H,H I think), so I'll need to roll back my other changes to test your inline fix.  That should also fix my linker warnings about some z80_ functions being defined multiple times.

I don't think Visual Studio supports __builtin_offsetof, as I'm getting a compiler error for that change.  I can't see it documented anywhere, though the VS documentation has grown steadily worse over the years.  As a short-term fix I'm including <stddef.h> and am defining it to be 'offsetof', though I know that's not a solution for Z.

**Comment by redcode** [comment]
I'll fix offsetof soon.

In the while, I'm going to simplify the callbacks to make them not depend on `<Z/types/generic functions.h>`. I'll submit the changes today.

I've made changes to the dynamic linker of ACME (my multiemulator) for that. Your project is not affected because you don't use the ABI, nor build its globals with `CPU_Z80_BUILD_ABI` / `CPU_Z80_BUILD_MODULE_ABI`. I'll give you tomorrow a single header with all the Z types and macros the core uses so you can make your project Z-free.

**Comment by redcode** [comment]
This issue was solved long ago.
